# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - saude-app-w7p5m8

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: saude.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7BA90D3B0F5541D896465A2D8A9605DA }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_D7E923CBDB9C4EDDA68B4662A9D48BC8 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: saude.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7BA90D3B0F5541D896465A2D8A9605DA }}/saude_web:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    

    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'saude-app-w7p5m8'
          slot-name: 'Production'
          images: 'saude.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_7BA90D3B0F5541D896465A2D8A9605DA }}/saude_web:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_97ED37302399413D819B957B7D78638D }}